// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpchkpgkfklleruwurzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwY2hrcGdrZmtsbGVydXd1cnprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczNDEwNTUsImV4cCI6MjA2MjkxNzA1NX0.xRuaaAMb67MZ919l2eJNwt-UWKfvxCYS45EDrt-YCfM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);